### ISSUE TITLE
Read babel config for output options

### ISSUE THREAD

**Issue by LegNeato** [nmn/swagger-to-js-api#8]
Some people may have different preferences, for example `function` longhand vs `() => {}` shorthand, Promises vs async/await, etc. It would be nice to point to a babel config and have the generator be smart enough to make the generated code conform to their desired style.

**Comment by nmn** [comment]
Interesting idea but actually making it work would be far too much work to actually be worth it.

In any case the generated code with flow types is compiled to es5 for use and so everyone should be able to use it.

Second this library is meant to be used for generating library code based on your API. In those cases code style shouldn't matter as no human should ever have to touch the generated code.
