### ISSUE TITLE
pipeThrough Example

### ISSUE THREAD

**Issue by naderhen** [nmn/swagger-to-js-api#9]
In the README you state: `The flow types give you errors when you pass in the wrong types of params, and also gives you the type definitions for the response object once you pipeThrough a function.`

Would it be possible to see an example of how this works?

**Comment by nmn** [comment]
so something like this:

```ts
import * as api from 'generated-api'

api.createUser(hostname, {name: 'bob'})
  .pipeThrough(axios)
  .then(res => res.data)
  .then(user => {/* user has types here */})
```

Some things to note:
1. You have to use the pipeThrough method to actually get the types to work.
2. Axios and $http (from angular 1) are currently the only 2 libraries that I know that work
3. The types will only be generated correctly if the source Swagger JSON file has the type information.

**Comment by naderhen** [comment]
Thanks, this is really helpful! Luckily we actually use axios in our target project so I should be able to give this a shot today. 

Thanks Again,
Nader
